version: '2'
services:
  backend:
    build:
      context: .
      dockerfile: ./etc/docker/backend/Dockerfile
    ports:
      - '3000:3000'
  frontend:
    restart: always
    build:
      context: .
      dockerfile: ./etc/docker/frontend/Dockerfile
    ports:
      - "80:80"
    links:
      - backend